### ISSUE TITLE
认证的地方为了兼容python3，添加了encode（）方法，其他地方可以仿照同样的方法进行修改

### ISSUE THREAD

**Issue by lonelyor** [aeonick/Aeonick#2]
文件：mylib
内容：
```   
    def verify(self,password=''):
        import hashlib
        #password = '123456'
        m = hashlib.md5(password.encode())
        m.update(password.encode())
        pd = m.hexdigest()
        print(self.password)
        print(m.hexdigest())
        if pd==self.password:
            return True
        else:
            return False
        #return True
```

**Comment by AlShelley** [comment]
你应该把加密后的字段和数据库取出的字段进行比较吧。

**Comment by lonelyor** [comment]
def verify(self,password=''):
        import hashlib
        m = hashlib.md5(password.encode())
        m.update(password.encode())
        pd = m.hexdigest()
        if pd==self.password:
            return True
        else:
            return False

**Comment by lonelyor** [comment]
def setPwd(self,old,new):
        import hashlib
        m = hashlib.md5(old.encode())
        m.update(old.encode())
        old_pd = m.hexdigest()
        if old_pd==self.password:
            m = hashlib.md5(new.encode())
            m.update(new.encode())
            new_pd = m.hexdigest()
            blogdb = get_db()
            cur = blogdb.cursor()
            cur.execute('UPDATE info SET content = ? where id = -3',(new_pd,))
            blogdb.commit()
            return 'Success'
        else:
            return "Couldn't match"

**Comment by aeonick** [comment]
感谢回复！确实这里写得容易引起误会。verify方法传入的password其实就是进行加密之后的字段。Py3在hash前必须把数据转成bytes类型，所以需要修改为m.update(password.encode('utf-8'))
